hand_landmarks_node:
  ros__parameters:
    image_topic: "/camera/color/image_raw"
    landmarks_topic: "/hand_landmarks"
    model_path: ""
    num_hands: 1
    min_hand_detection_confidence: 0.5
    min_hand_presence_confidence: 0.5
    min_tracking_confidence: 0.5
    running_mode: "LIVE_STREAM" # Options: "IMAGE", "VIDEO", "LIVE_STREAM"
    enable_one_euro_filter: true
    one_euro_frequency: 30.0
    one_euro_mincutoff: 5.
    one_euro_beta: 100.
    visualize: true
    window_name: "Hand Landmarks (Node)"
    
